clear s; clear all;
%%addpath('./ThirdParty/STLRead');

% Dependencies: reads from the serial port the messages generated by the
% webserial_3d.ino firmware. Check the "Adafruit BNO055" library.

% change this accordingly (tested under Windows)
serialportname = "COM13";
baudrate = 9600;

f = figure(1);
[verts, faces, cindex] = teapotGeometry;
fv.vertices = verts;
fv.faces = faces;

%fv = stlread('../v5.stl');
fvtemp = fv;

%p = patch('Faces',faces,'Vertices',verts,'FaceColor','interp');
patch(fv,'FaceColor',       [0.8 0.8 1.0], ...
         'EdgeColor',       'none',        ...
         'FaceLighting',    'gouraud',     ...
         'AmbientStrength', 0.15);
% Add a camera light, and tone down the specular highlighting
camlight('headlight');
material('dull');

axis equal off 
view(-151,30) 

ButtonHandle = uicontrol('Style', 'PushButton', ...
                         'String', 'Stop loop', ...
                         'Callback', 'delete(gcbf)');

s = serialport(serialportname,baudrate);

q1 = 0.0;
q2 = 0.0;
q3 = 0.0;
q4 = 0.0;
qf = quaternion(q1,q2,q3,q4);

while(1)
    
    dataline = readline(s);
    dataparts = strsplit(dataline);
    if dataparts(1) == "Quaternion:"
        cla;
        q1 = str2double(dataparts(2));
        q2 = str2double(dataparts(3));
        q3 = str2double(dataparts(4));
        q4 = str2double(dataparts(5));
        qf = quaternion(q1,q2,q3,q4);
        %%verts2 = rotateframe(qf,verts);
        fvtemp.vertices = rotateframe(qf,fv.vertices);
        %ax = plotTransforms([0 0 0],[0 0 0 0])
        %%p = patch('Faces',faces,'Vertices',verts2,'FaceVertexCData',cindex,'FaceColor','interp');
        % Add a camera light, and tone down the specular highlighting
        patch(fvtemp,'FaceColor',       [0.8 0.8 1.0], ...
         'EdgeColor',       'none',        ...
         'FaceLighting',    'gouraud',     ...
         'AmbientStrength', 0.15);
        camlight('headlight');
        material('dull');
        
    end
    [q1,q2,q3,q4]
    
    if ~ishandle(ButtonHandle)
        disp('Loop stopped by user');
        clear s; % Cleaning the serial port handlers
        clf;
        break;
    end
end